---
- name: Install packages required for Ansible to manage Python
  become: true
  yum:
    name:
      - python-setuptools

- name: Install system Python 3 core packages
  become: true
  yum:
    name:
      - python3
      - python3-pip
      - python3-setuptools
    state: "{{ python3_core_state }}"
    # TODO This would be a good place to install libselinux for python3 if it existed.
    # But it doesn't (yet), see discussions at:
    # https://bugzilla.redhat.com/show_bug.cgi?id=1756015
    # https://bugs.centos.org/view.php?id=16389

- name: Install additional packages for system Python 3
  become: true
  yum:
    name: "{{ python3_pkgs }}"
    state: "{{ python3_pkgs_state }}"

- name: Create python3 user to own shared pip packages
  become: true
  user:
    name: python3
    shell: /sbin/nologin

- name: Make a home for shared pip packages
  become: true
  file:
    path:  /opt/python3
    owner: python3
    state: directory
    mode: '0755'

- name: Install shared Python3 pip packages
  become: true
  become_user: python3
  pip:
    executable: /usr/bin/pip3
    extra_args: --prefix  /opt/python3
    name: "{{ python3_pip_pkgs }}"

- name: Add shared pip-installed tools to PATH for users
  copy:
    dest: "/etc/profile.d/python3.sh"
    content: |
      export PATH="${PATH}:/opt/python3/bin"

# contents of .pth file are added to sys.pth
# See https://docs.python.org/3/library/site.html
- name: Add shared pip-installed  modules to system Python 3 PYTHONPATH
  copy:
    dest: "/usr/lib/python3.6/site-packages/optpython.pth"
    content: |
      /opt/python3/lib/python3.6/site-packages/
      /opt/python3/lib64/python3.6/site-packages/
