---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_roles, profile_tasks, timer in the ansible.cfg 
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
